version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - copyloopvar
    - errorlint
    - gocritic
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: exported
        - name: error-return
        - name: error-naming
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gocritic
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/RaduAndreiTudorica/raftkv
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
