FROM golang:1.27 AS builder

WORKDIR /app

COPY go.sum go.mod ./
RUN go mod download

COPY ./ ./

RUN CGO_ENABLED=0 go build -o /raftkv-cli ./cmd/raftkv-cli

FROM alpine
COPY --from=builder /raftkv-cli /raftkv-cli

ENTRYPOINT ["/raftkv-cli"]
CMD ["--addrs", "host.docker.internal:60000,host.docker.internal:60001,host.docker.internal:60002"]
